url: http://fumiyas.github.io
title: "ダメ出し Blog"
author: "SATOH Fumiyasu (佐藤 文優, fumiyas)"
markdown: redcarpet
redcarpet:
  extensions: [no_intra_emphasis,tables,autolink,strikethrough,space_after_headers]

