url: https://fumiyas.github.io
host: fumiyas.github.io
github:
  root: https://github.com
  repo: fumiyas/fumiyas.github.io
twitter:
  id: satoh_fumiyasu
  tweet: https://twitter.com/?status=
title: "ダメ出し Blog"
author: "SATOH Fumiyasu (佐藤 文優, fumiyas)"
markdown: kramdown

